# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ven_Nombre.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VenNombre(object):
    def setupUi(self, VenNombre):
        VenNombre.setObjectName("VenNombre")
        VenNombre.resize(400, 300)
        self.btnBoxNombre = QtWidgets.QDialogButtonBox(VenNombre)
        self.btnBoxNombre.setGeometry(QtCore.QRect(-50, 180, 341, 32))
        self.btnBoxNombre.setOrientation(QtCore.Qt.Horizontal)
        self.btnBoxNombre.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btnBoxNombre.setObjectName("btnBoxNombre")
        self.lblMensaje = QtWidgets.QLabel(VenNombre)
        self.lblMensaje.setGeometry(QtCore.QRect(110, 60, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblMensaje.setFont(font)
        self.lblMensaje.setObjectName("lblMensaje")
        self.editNombre = QtWidgets.QLineEdit(VenNombre)
        self.editNombre.setGeometry(QtCore.QRect(110, 130, 191, 20))
        self.editNombre.setObjectName("editNombre")

        self.retranslateUi(VenNombre)
        self.btnBoxNombre.accepted.connect(VenNombre.accept)
        self.btnBoxNombre.rejected.connect(VenNombre.reject)
        QtCore.QMetaObject.connectSlotsByName(VenNombre)

    def retranslateUi(self, VenNombre):
        _translate = QtCore.QCoreApplication.translate
        VenNombre.setWindowTitle(_translate("VenNombre", "Dialog"))
        self.lblMensaje.setText(_translate("VenNombre", "INTRODUCE UN NOMBRE"))
