# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ven_chocar.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ven_Chocar(object):
    def setupUi(self, Ven_Chocar):
        Ven_Chocar.setObjectName("Ven_Chocar")
        Ven_Chocar.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ven_Chocar.sizePolicy().hasHeightForWidth())
        Ven_Chocar.setSizePolicy(sizePolicy)
        Ven_Chocar.setSizeIncrement(QtCore.QSize(0, 0))
        self.btnBoxChocar = QtWidgets.QDialogButtonBox(Ven_Chocar)
        self.btnBoxChocar.setGeometry(QtCore.QRect(-50, 180, 341, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBoxChocar.sizePolicy().hasHeightForWidth())
        self.btnBoxChocar.setSizePolicy(sizePolicy)
        self.btnBoxChocar.setOrientation(QtCore.Qt.Horizontal)
        self.btnBoxChocar.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btnBoxChocar.setObjectName("btnBoxChocar")
        self.lblChocar = QtWidgets.QLabel(Ven_Chocar)
        self.lblChocar.setGeometry(QtCore.QRect(70, 60, 271, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblChocar.sizePolicy().hasHeightForWidth())
        self.lblChocar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.lblChocar.setFont(font)
        self.lblChocar.setObjectName("lblChocar")

        self.retranslateUi(Ven_Chocar)

        QtCore.QMetaObject.connectSlotsByName(Ven_Chocar)

    def retranslateUi(self, Ven_Chocar):
        _translate = QtCore.QCoreApplication.translate
        Ven_Chocar.setWindowTitle(_translate("Ven_Chocar", "Dialog"))
        self.lblChocar.setText(_translate("Ven_Chocar", "HAS CHOCADO"))
