# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VenChocar.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VenChocar(object):
    def setupUi(self, VenChocar):
        VenChocar.setObjectName("VenChocar")
        VenChocar.resize(1005, 611)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VenChocar.sizePolicy().hasHeightForWidth())
        VenChocar.setSizePolicy(sizePolicy)
        VenChocar.setMouseTracking(False)
        VenChocar.setAcceptDrops(False)
        VenChocar.setLayoutDirection(QtCore.Qt.LeftToRight)
        VenChocar.setAutoFillBackground(False)
        VenChocar.setStyleSheet("\\")
        VenChocar.setAnimated(False)
        VenChocar.setDocumentMode(False)
        VenChocar.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(VenChocar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("image: url(:/newPrefix/fondo_menu.png);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem, 1, 2, 1, 1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setSpacing(6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.btnJugar = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnJugar.sizePolicy().hasHeightForWidth())
        self.btnJugar.setSizePolicy(sizePolicy)
        self.btnJugar.setMinimumSize(QtCore.QSize(200, 50))
        self.btnJugar.setAutoFillBackground(False)
        self.btnJugar.setObjectName("btnJugar")
        self.gridLayout_12.addWidget(self.btnJugar, 0, 0, 1, 1)
        self.btnSalir = QtWidgets.QPushButton(self.centralwidget)
        self.btnSalir.setMinimumSize(QtCore.QSize(200, 50))
        self.btnSalir.setAutoFillBackground(False)
        self.btnSalir.setStyleSheet("")
        self.btnSalir.setObjectName("btnSalir")
        self.gridLayout_12.addWidget(self.btnSalir, 1, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_12, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem3, 4, 1, 1, 1)
        VenChocar.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VenChocar)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1005, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setObjectName("menubar")
        VenChocar.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VenChocar)
        self.statusbar.setObjectName("statusbar")
        VenChocar.setStatusBar(self.statusbar)

        self.retranslateUi(VenChocar)
        QtCore.QMetaObject.connectSlotsByName(VenChocar)

    def retranslateUi(self, VenChocar):
        _translate = QtCore.QCoreApplication.translate
        VenChocar.setWindowTitle(_translate("VenChocar", "Drunk Driver"))
        self.btnJugar.setText(_translate("VenChocar", "Jugar"))
        self.btnSalir.setText(_translate("VenChocar", "Salir"))
import menu
